package unicam.spm2023.selenium;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.*;

public class SeleniumIDETest {
  private static WebDriver driver;
  private static Map<String, Object> vars;
  static JavascriptExecutor js;

  static ChromeOptions options = new ChromeOptions();
  @BeforeAll
  public static void setUp() {
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public static void tearDown() {
    driver.close();
    driver.quit();
  }
  @Test
  public void searchonPROSSite() {
    // Test name: Search on PROS Site
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://pros.unicam.it/");
    // 2 | setWindowSize | 1223x986 | 
    driver.manage().window().setSize(new Dimension(1223, 986));
    // 3 | click | id=svg-search | 
    driver.findElement(By.id("svg-search")).click();
    // 4 | click | name=s | 
    driver.findElement(By.name("s")).click();
    // 5 | type | name=s | digital twin
    driver.findElement(By.name("s")).sendKeys("digital twin");
    // 6 | sendKeys | name=s | ${KEY_ENTER}
    driver.findElement(By.name("s")).sendKeys(Keys.ENTER);
  }
}
